### ISSUE TITLE
Subsequent channel point redemptions don't appear to be redeemed.

### ISSUE THREAD

**Issue by cerulliulliulli** [j3channel/StreamElementsWidgets#1]
Redeeming the same channel point redemption back to back, even within the queue window, doesn't seem to allow the playback of the second redemption's video.

A third redemption will play. Occasionally, if two redemptions are redeemed with a regular line of text in between, it will also playback without issue.

**Comment by j3channel** [comment]
Hey cerulliulliulli,

Could you open your browser's inspector window (usually Ctrl + Shift + J) and provide me with the logs when this occurs?
The widget should log while it performs actions, so this can help me track down the issue.

Also, how quickly are the redemptions being redeemed? Are we talking within milliseconds or approximately 1-2 seconds between?

**Comment by j3channel** [comment]
May I also ask what type of video file you are using?

I am using .webm files (my personal preference) and have been trying to replicate this issue for a short while now, using a video that lasts approximately 5 seconds.

I have opened 7 separate instances of our chat and am redeeming the same channel point reward back-to-back from each window approximately 0.5s between each other. The video appears to play back 7 times without any issues.

**Comment by cerulliulliulli** [comment]
They're all .webm's using VP8 (I noticed issues with VP9 on playback for separate reasons with Stream Elements). The clips in this case are much shorter, between 1-3 seconds. On average 2 seconds?

I reduced the wait time from 1 second to 0 on the queue refresh but the issue persisted. I was able to replicate it consistently but as the connection runs in the background on Stream Elements I can't actually see what's being logged if anything.

Is it possible the issue presents itself with some back-end issue on the Twitch side, maybe inconsistent availability from their IRC server? I know they have "chat" issues relatively often, whether that be front or back-end I don't know.

I actually just brought up a fresh instance and can't reproduce it now. So maybe either something that happens over time from the client "listening" to redeems in chat (I redeemed a lot while tweaking the CSS), or a Twitch issue. 

Additionally, there's one particular .webm that will not playback no matter what I export it as or name the redeem, or the order in which I have it in the Redemptions list. Still not sure about that one but it's less important, the other 9 work excellently. This is an amazing widget.

**Comment by j3channel** [comment]
The queue time is set to 1s on purpose, just so it's not constantly polling every few ms to see if the current reward has finished and if there's another in the queue. Setting it to 0s caused me some issues, so I set it to 1. You could try setting it to 2-3s and see if it helps?

I am able to see what is being logged from the widget, so you should also be able to see it in the browser's console. All logs from this widget should be prefixed with `[VIDEO PLAYER] -` so you can easily determine where the logs are coming from.

I have noticed with the SE Client that sometimes multiple widgets on one overlay can cause some to have issues. I think if some widgets have variables in a script with the same name as variables in another, they seem to cross over! I know it sounds weird, but try putting the widget on its own overlay if you haven't already. Luckily browser sources use very little resources, so shouldn't cause you any OBS issues.

That's very strange with that one particular .webm file - unfortunately can't explain that one!

**Comment by j3channel** [comment]
Also, to add to your comment about the issue being Twitch-side, I haven't yet experienced the PubSub to ever _not_ pass through a Channel Points event - it is pretty reliable from what I've seen as I use it in a lot of widgets!

So I think, as much as it pains me to say it, if there is an issue it would be my widget side!

**Comment by cerulliulliulli** [comment]
I didn't think about increasing it, but I'll give that a shot. Although I had misunderstood how the queue works and thought subsequent redeems would be skipped if something was active while another was redeemed, that makes more sense!

Thanks for the tip about the console. I'll be using the widget live for the first time so I'll get a chance to see it in action (at 1ms again, not 0ms) but I haven't been able to reproduce it since I opened the issue as it was reproducible for an hour, at least. Of course that would happen.

I'll also test out a unique source--SE seems to be half-baked when it comes to a few scripts. The others that I've created were purpose-built to avoid that but I wouldn't be surprised if it's still happening.

I think we can close this. Thanks for the awesome widget, looking forward to testing the rest of what you've done!

**Comment by j3channel** [comment]
I can definitely see the misunderstanding! No, all redemptions get popped into a queue and the queue timer is just how often (in seconds, not milliseconds!) the queue will check to see if it is clear to play the next item in the queue.

I am glad you haven’t been able to reproduce it, but if it happens again please either re-open this or create a new one so I can properly investigate.

Agreed. Sometimes I do purposely try to avoid conflicting naming conventions just in case SE gets confused! Hopefully separating it can ensure it never does, at least.

Best of luck with your streams! Hope it works well for you and thanks for the kind words!
